project:
  type: website

website:
  title: "Estatistica Espacial"
  sidebar:
    style: floating   # <- Isso ativa o menu retrátil
    collapse-level: 1
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - Capitulo1.qmd

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true



