project:
  type: website

website:
  title: "Estatistica Espacial"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - Capitulo1.qmd

format:
  html:
    theme: 
      light: Yeti
      dark: darkly
    css: styles.css
    toc: true



